#!/bin/bash
wget -O- http://archive.apache.org/dist/bigtop/bigtop-0.5.0/repos/GPG-KEY-bigtop | apt-key add -
wget -O /etc/apt/sources.list.d/bigtop-0.5.0.list http://archive.apache.org/dist/bigtop/bigtop-0.5.0/repos/`lsb_release --codename --short`/bigtop.list
### 更新套件庫
apt-get -y update
### 安裝 BigTop Utility
apt-get -y install bigtop-utils
### 安裝 Oracle Java Runtime and JDK
if [ ! -x /usr/bin/add-apt-repository ]; then
    sudo apt-get -f -y install python-software-properties
fi

if [ ! -x /usr/bin/java ]; then
    echo "---- [1] Installing Sun Java JDK 6 ........ ----"
    sudo add-apt-repository -y 'deb http://free.nchc.org.tw/debian squeeze non-free'
    sudo apt-get update
    cat << EOF | sudo /usr/bin/debconf-set-selections
sun-java6-bin   shared/accepted-sun-dlj-v1-1    select true
sun-java6-jdk   shared/accepted-sun-dlj-v1-1    select true
sun-java6-jre   shared/accepted-sun-dlj-v1-1    select true
EOF
    sudo apt-get -y --force-yes install sun-java6-jdk
    sudo add-apt-repository -r 'deb http://free.nchc.org.tw/debian squeeze non-free'
fi

### 設定 JAVA_HOME 到 BigTop Utility 預設值
echo "export JAVA_HOME=/usr/lib/jvm/java-6-sun" >> /etc/default/bigtop-utils 
### 安裝 Hadoop 相關套件
apt-get -y install hadoop-hdfs\* hadoop-mapreduce\*
